import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.qrComponent}>
          <Image
            className={styles.logo}
            src="/image-qr-code.png"
            alt="QR Code"
            width={400}
            height={400}
            priority
          />
          <h1 className={styles.center}>
            Improve your front-end skills by building projects
          </h1>
          <p className={styles.center}>
            Scan the QR code to visit Frontend Mentor and take your coding
            skills to next level
          </p>
        </div>
      </main>
    </Layout>
  );
}
